### ISSUE TITLE
great work!

### ISSUE THREAD

**Issue by 1c7** [josegomezr/the-super-tiny-compiler#1]
The Python version is actually  more clear than Node.js version.
Thank you

**Comment by josegomezr** [comment]
Thanks, any suggestions are welcome!

**Comment by 1c7** [comment]
the musical instrument in your portrait, what is that? name?
never seen something like that.
seem fun.
:smiley:

**Comment by josegomezr** [comment]
It's a Venezuelan Cuatro. It looks like an Ukelele but its tuning its different.

**Comment by 1c7** [comment]
LOL 
Learned something new.
